### ISSUE TITLE
无法下载并提示connection refused

### ISSUE THREAD

**Issue by MineCreeper86** [osupink/osu-download#1]
软件版本：b20200617.2
网络环境：上海 移动
返回信息：{**"msg"**:"connection refused",**"code"**:"50302004",**"id"**:"c47a************************7a9f"}

**Comment by kj415j45** [comment]
目前镜像服务器已全部关闭，如有需求可前往 osu.sayobot.cn

**Comment by lslqtz** [comment]
确实，挂了半年了
这一问题预计将在一周内修复，如有疑问优先建议入群询问

**Comment by lslqtz** [comment]
经测试，现已恢复，刚好一周
内有包含对 Sayobot 的支持
