### ISSUE TITLE
文件感染病毒

### ISSUE THREAD

**Issue by wwwab123** [osupink/osu-download#2]
Synares家族的感染型病毒携带者

**Comment by lslqtz** [comment]
感谢反馈，我的设备在最近几次编译前中毒了，表示抱歉。
这件事我也是今天才发现的。
我将更新一版新版本，并同时提供杀毒程式。

**Comment by lslqtz** [comment]
已对设备进行杀毒，并重新编译新版本，这一版本和上一版本相同，但其产出文件不带毒，已通过 VirScan 报告检测，专杀软件一并附上。
https://github.com/osupink/osu-download/releases/tag/b20211017.1f
非常感谢！
